### PR TITLE
Add initial simple integration test

### PR DESCRIPTION
**Pull request by c0d1ngm0nk3y**
## Summary

It adds a first integration test to this buildpack. The integration test verifies that the buildplan is as expected and makes sure that it can be build and the `Procfile` is taken into account.

## Use Cases

* For local development to verify the local state
* As pr validation to make sure that the pr is not breaking the existing test
* Add future tests since it is easier to add to an existing test suite than to create everything

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by dmikusa** [comment]
My problem with this is that it requires Node.js buildpacks which are unrelated to procfile, and this Procfile project has to keep up with Node.js changes as well. It couples the two together, even if it's not a strong coupling there's some coupling. 

My preference would be for no external buildpacks, if we are going to add integration tests at all (I'd personally rather see integration tests happening at the composite buildpack level). If that means we have to have a test fixture buildpack to mock the requirements of Procfile, I would rather see that than start pulling dependencies on other buildpacks.

**Comment by c0d1ngm0nk3y** [comment]
> My problem with this is that it requires Node.js buildpacks which are unrelated to procfile, and this Procfile project has to keep up with Node.js changes as well. It couples the two together, even if it's not a strong coupling there's some coupling.
> 

I wouldn't call this coupling. Sure, they have to work together, but this is exactly what the integration test should make sure.

> My preference would be for no external buildpacks, if we are going to add integration tests at all (I'd personally rather see integration tests happening at the composite buildpack level).

But isn't that to late? On composite level, any problem would only be found after the release of the component buildpack. Or am I missing something?

> If that means we have to have a test fixture buildpack to mock the requirements of Procfile, I would rather see that than start pulling dependencies on other buildpacks.

Sounds like a test that would be good to have to me, but is this really a substitute? Sounds rather like an addition to me.

Maybe I am to naive or missing something, but how to develop something on the `Procfile buildback` and make sure to not break something? I would end up doing the steps of the integration test manually, wouldn't I?

**Comment by c0d1ngm0nk3y** [comment]
@dmikusa I have removed the dependency to other buildpacks. Except `build-plan`, but that should be OK for a test. Could you have a second look? I still think the test adds some value for both, local validation and PR validation.

**Comment by dmikusa** [comment]
My vote on this would be -1. I don't feel like it's necessary and I don't feel like the benefits outweigh the cost.

My rationale:

1. Adding tests that run the buildpacks is significantly slower (COST)
2. It pulls in many additional Go dependencies. While these dependencies are test-only and don't contribute to the binary size, they are a huge pain to manage and keep up-to-date. These dependencies frequently get flagged as having CVEs, which flags the entire buildpack as vulnerable. I've also had trouble with transitive dependencies being broken and breaking our update pipelines (this happened on Apache Tomee). (COST x2)
3. I don't see a use case that cannot be tested in the way we're presently testing things. The test case that's added in this PR is testing the same thing that we test in `build_test.go`.

Sorry, I'm not seeing the value of running the buildpack in a set of tests in this buildpack. I think we should focus on adding the proposed level of testing to our composite buildpacks. 

On the Java side, we've just recently merged an RFC that clears the way to run this style of tests in paketo-buildpacks/java.  That should be coming soon and that will also exercise the procfile buildpack.

**Comment by c0d1ngm0nk3y** [comment]
I guess we can close this if nobody sees any benefit in having an integration test verifying the buildpack as a whole.

**Pull request closed without merging**
